_commit: 27a2778
_src_path: gh:ChuckieChen945/substrate
author_email: chuckie_chen@outlook.com
author_name: Chuckie Chen
project_description: My personal python utils
project_name: long_sword
project_type: package
project_url: https://github.com/ChuckieChen945/long_sword
python_version: '3.10'
typing: strict
with_conventional_commits: true
with_typer_cli: false
